# Generated by Django 5.1.15 on 2025-12-24 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='appointmenthistory',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmenthistory',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='BookingLock',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='oroshine_we_user_id_7d35b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='oroshine_we_service_bd10f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='oroshine_we_status_021d8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='oroshine_we_email_f43044_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsletter',
            name='oroshine_we_email_47d752_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='oroshine_we_created_3fabd9_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00 AM'), ('09:30', '09:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('14:00', '02:00 PM'), ('14:30', '02:30 PM'), ('15:00', '03:00 PM'), ('15:30', '03:30 PM'), ('16:00', '04:00 PM'), ('16:30', '04:30 PM'), ('17:00', '05:00 PM')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'status', 'date'], name='oroshine_we_user_id_d08fff_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor_email', 'date', 'status'], name='oroshine_we_doctor__4a86c3_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'created_at'], name='oroshine_we_user_id_065a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['is_active', 'subscribed_at'], name='oroshine_we_is_acti_523245_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['city', 'created_at'], name='oroshine_we_city_715d06_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'code'], name='oroshine_we_is_acti_1b5042_idx'),
        ),
        migrations.DeleteModel(
            name='AppointmentHistory',
        ),
    ]
