# Generated by Django 5.0.1 on 2025-08-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
    ]
