# Generated by Django 5.1.15 on 2025-12-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0002_service_remove_appointmenthistory_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00 AM'), ('09:15', '09:15 AM'), ('09:30', '09:30 AM'), ('09:45', '09:45 AM'), ('10:00', '10:00 AM'), ('10:15', '10:15 AM'), ('10:30', '10:30 AM'), ('10:45', '10:45 AM'), ('11:00', '11:00 AM'), ('11:15', '11:15 AM'), ('11:30', '11:30 AM'), ('11:45', '11:45 AM'), ('12:00', '12:00 PM'), ('12:15', '12:15 PM'), ('12:30', '12:30 PM'), ('12:45', '12:45 PM'), ('13:00', '01:00 PM'), ('13:15', '01:15 PM'), ('13:30', '01:30 PM'), ('13:45', '01:45 PM'), ('14:00', '02:00 PM'), ('18:00', '06:00 PM'), ('18:15', '06:15 PM'), ('18:30', '06:30 PM'), ('18:45', '06:45 PM'), ('19:00', '07:00 PM'), ('19:15', '07:15 PM'), ('19:30', '07:30 PM'), ('19:45', '07:45 PM'), ('20:00', '08:00 PM'), ('20:15', '08:15 PM'), ('20:30', '08:30 PM'), ('20:45', '08:45 PM'), ('21:00', '09:00 PM')], db_index=True, max_length=5),
        ),
    ]
