# Generated by Django 5.0.1 on 2025-09-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
