# Generated by Django 5.1.15 on 2025-12-26 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0003_alter_appointment_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='oroshine_we_date_c2a867_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='oroshine_we_user_id_d08fff_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_slot_lookup',
            old_name='oroshine_we_doctor__4a86c3_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', '-date'], name='idx_user_appointments'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'status'], name='idx_reminder_scan'),
        ),
    ]
